//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::category::Entity as Category;
pub use super::post::Entity as Post;
pub use super::post_category::Entity as PostCategory;
pub use super::post_tag::Entity as PostTag;
pub use super::tag::Entity as Tag;
